[tool.poetry]
name = "syntax-checker"
version = "0.1.0"
description = "A Python syntax checker module."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
